databases:
  - name: Promise
    databaseName: promise_0taz
    user: promise_0taz_user

services:
  - type: web
    name: My Recipe
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: promise_0taz
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false