require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe '/recipe_items', type: :request do
  # This should return the minimal set of attributes required to create a valid
  # RecipeItem. As you add validations to RecipeItem, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) do
    skip('Add a hash of attributes valid for your model')
  end

  let(:invalid_attributes) do
    skip('Add a hash of attributes invalid for your model')
  end

  describe 'GET /index' do
    it 'renders a successful response' do
      RecipeItem.create! valid_attributes
      get recipe_items_url
      expect(response).to be_successful
    end
  end

  describe 'GET /show' do
    it 'renders a successful response' do
      recipe_item = RecipeItem.create! valid_attributes
      get recipe_item_url(recipe_item)
      expect(response).to be_successful
    end
  end

  describe 'GET /new' do
    it 'renders a successful response' do
      get new_recipe_item_url
      expect(response).to be_successful
    end
  end

  describe 'GET /edit' do
    it 'renders a successful response' do
      recipe_item = RecipeItem.create! valid_attributes
      get edit_recipe_item_url(recipe_item)
      expect(response).to be_successful
    end
  end

  describe 'POST /create' do
    context 'with valid parameters' do
      it 'creates a new RecipeItem' do
        expect do
          post recipe_items_url, params: { recipe_item: valid_attributes }
        end.to change(RecipeItem, :count).by(1)
      end

      it 'redirects to the created recipe_item' do
        post recipe_items_url, params: { recipe_item: valid_attributes }
        expect(response).to redirect_to(recipe_item_url(RecipeItem.last))
      end
    end

    context 'with invalid parameters' do
      it 'does not create a new RecipeItem' do
        expect do
          post recipe_items_url, params: { recipe_item: invalid_attributes }
        end.to change(RecipeItem, :count).by(0)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post recipe_items_url, params: { recipe_item: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe 'PATCH /update' do
    context 'with valid parameters' do
      let(:new_attributes) do
        skip('Add a hash of attributes valid for your model')
      end

      it 'updates the requested recipe_item' do
        recipe_item = RecipeItem.create! valid_attributes
        patch recipe_item_url(recipe_item), params: { recipe_item: new_attributes }
        recipe_item.reload
        skip('Add assertions for updated state')
      end

      it 'redirects to the recipe_item' do
        recipe_item = RecipeItem.create! valid_attributes
        patch recipe_item_url(recipe_item), params: { recipe_item: new_attributes }
        recipe_item.reload
        expect(response).to redirect_to(recipe_item_url(recipe_item))
      end
    end

    context 'with invalid parameters' do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        recipe_item = RecipeItem.create! valid_attributes
        patch recipe_item_url(recipe_item), params: { recipe_item: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe 'DELETE /destroy' do
    it 'destroys the requested recipe_item' do
      recipe_item = RecipeItem.create! valid_attributes
      expect do
        delete recipe_item_url(recipe_item)
      end.to change(RecipeItem, :count).by(-1)
    end

    it 'redirects to the recipe_items list' do
      recipe_item = RecipeItem.create! valid_attributes
      delete recipe_item_url(recipe_item)
      expect(response).to redirect_to(recipe_items_url)
    end
  end
end
